### ISSUE TITLE
Error ingesting package: 

### ISSUE THREAD

**Issue by emetsger** [DataConservancy/dcs-package-ingest#3]
### Fedora Jetty Log

Transaction inexplicably rolled back

> INFO 18:04:09.538 (FedoraLdp) Ingest with path: /Frank Sinatra/Blue Skies/92ab045e2cbf72507d195050886a3ba9a7656c40
> INFO 18:04:09.582 (FedoraLdp) Ingest with path: /Frank Sinatra/Blue Skies/92ab045e2cbf72507d195050886a3ba9a7656c40/06 Dream, Dream, Dream.mp3
> INFO 18:04:09.728 (FedoraTransactions) Rollback transaction 'tx:890fb4d1-951c-448e-816c-95cb62595837'

### Karaf Log

> java.lang.IllegalArgumentException: Invalid uri: %20Dream.mp3/fcr:metadata. If you are forwarding/bridging http endpoints, then enable the bridgeEndpoint option on the endpoint: Endpoint[http4://ldp-host?throwExceptionOnFailure=false]

**Comment by emetsger** [comment]
Original package: https://drive.google.com/file/d/0BywY-llM1_-5VXBKUVlaTmRwODQ/view?usp=sharing

**Comment by emetsger** [comment]
> org.apache.camel.CamelExchangeException: Sequential processing failed for number 0. Exchange[ID-ced9c4a6db3b-44470-1463766433128-0-2349][Message: org.dataconservancy.packaging.impl.BasicLdpResource@196121d8]. Caused by: [org.apache.camel.CamelExchangeException - Sequential processing failed for number 0. Exchange[ID-ced9c4a6db3b-44470-1463766433128-0-2353][Message: org.dataconservancy.packaging.impl.BasicLdpResource@196121d8]. Caused by: [org.apache.camel.CamelExchangeException - Sequential processing failed for number 0. Exchange[ID-ced9c4a6db3b-44470-1463766433128-0-2362][Message: org.dataconservancy.packaging.impl.BasicLdpResource@5523ffee]. Caused by: [org.apache.camel.CamelExchangeException - Sequential processing failed for number 10. Exchange[ID-ced9c4a6db3b-44470-1463766433128-0-2621][Message: org.dataconservancy.packaging.impl.BasicLdpResource@532d4c5]. Caused by: [org.apache.camel.CamelExchangeException - Sequential processing failed for number 0. Exchange[ID-ced9c4a6db3b-44470-1463766433128-0-2630][Message: INSERT {
> <http://localhost:8080/fcrepo/rest/tx:c52668b1-d448-4354-ba68-92854dea7a19/Frank%20Sinatra/Blue%20Skies/92ab045e2cbf72507d195050886a3ba9a7656c40/06%20Dream,%20Dream,%20Dream.mp3> <http://dataconservancy.org/business-object-model#isMemberOf> <http://localhost:8080/fcrepo/rest/tx:c52668b1-d448-4354-ba68-92854dea7a19/Frank%20Sinatra/Blue%20Skies/92ab045e2cbf72507d195050886a3ba9a7656c40> .
> <http://localhost:8080/fcrepo/rest/tx:c52668b1-d448-4354-ba68-92854dea7a19/Frank%20Sinatra/Blue%20Skies/92ab045e2cbf72507d195050886a3ba9a7656c40/06%20Dream,%20Dream,%20Dream.mp3> <http://dataconservancy.org/business-object-model#hasTitle> "06 Dream, Dream, Dream.mp3" .
> <http://localhost:8080/fcrepo/rest/tx:c52668b1-d448-4354-ba68-92854dea7a19/Frank%20Sinatra/Blue%20Skies/92ab045e2cbf72507d195050886a3ba9a7656c40/06%20Dream,%20Dream,%20Dream.mp3> <http://dataconservancy.org/business-object-model#hasSize> "4367070"^^<http://www.w3.org/2001/XMLSchema#long> .
> <http://localhost:8080/fcrepo/rest/tx:c52... [Body clipped after 1000 chars, total length is 2405]]. Caused by: [java.lang.IllegalArgumentException - Invalid uri: %20Dream.mp3/fcr:metadata. If you are forwarding/bridging http endpoints, then enable the bridgeEndpoint option on the endpoint: Endpoint[http4://ldp-host?throwExceptionOnFailure=false]]]]]]
> at org.apache.camel.processor.MulticastProcessor.doProcessSequential(MulticastProcessor.java:616)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.MulticastProcessor.process(MulticastProcessor.java:237)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Splitter.process(Splitter.java:104)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:115)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:86)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:141)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:115)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.TryProcessor.process(TryProcessor.java:86)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.component.direct.DirectProducer.process(DirectProducer.java:62)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:141)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.management.InstrumentationProcessor.process(InstrumentationProcessor.java:77)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:460)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:121)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.Pipeline.process(Pipeline.java:83)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:190)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.component.file.GenericFileConsumer.processExchange(GenericFileConsumer.java:442)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.component.file.GenericFileConsumer.processBatch(GenericFileConsumer.java:214)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.component.file.GenericFileConsumer.poll(GenericFileConsumer.java:178)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)[101:org.apache.camel.camel-core:2.16.1]
> at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)[101:org.apache.camel.camel-core:2.16.1]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_77-internal]
> at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)[:1.8.0_77-internal]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)[:1.8.0_77-internal]
> at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)[:1.8.0_77-internal]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_77-internal]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_77-internal]
> at java.lang.Thread.run(Thread.java:745)[:1.8.0_77-internal]
